apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Path              /var/log/nginx/access.log
        Tag               nginx.access
        Parser            nginx
        DB                /var/log/flb_nginx.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name           log_to_metrics
        Match          nginx.*
        Metric         counter nginx_http_requests_total
        Value_Field    status
        Label_Field    status
        Add_Label      app nginx

    [OUTPUT]
        Name              prometheus_exporter
        Match             *
        Host              0.0.0.0
        Port              2020

  parsers.conf: |
    [PARSER]
        Name   nginx
        Format regex
        Regex  ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>\d{3}) (?<body_bytes_sent>\d+) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)"
        Time_Key time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z
