apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name   tail
        Path   /var/log/nginx/access.log
        Parser nginx
        Tag    nginx

    [FILTER]
        Name   log_to_metrics
        Match  nginx
        Metric nginx_requests_total counter 1
        Metric nginx_status_codes   counter 1 label:status

    [OUTPUT]
        Name  prometheus_remote_write
        Match *
        Host  victoria-metrics.monitoring.svc.cluster.local
        Port  8428
        Uri   /api/v1/write
