apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
        ports:
          - name: http-metrics
            containerPort: 2020
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc/
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
