apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/nginx/access.log
        Tag               nginx.access
        Parser            nginx
        DB                /var/log/flb_nginx.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name          log_to_metrics
        Match         nginx.*
        Metric_Mode   counter
        Metric_Name   nginx_http_requests_total
        Value_Field   body_bytes_sent
        Add_Label     status

    [OUTPUT]
        Name              prometheus_exporter
        Match             *
        Host              0.0.0.0
        Port              2020

  parsers.conf: |
    [PARSER]
        Name   nginx
        Format regex
        Regex  ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>\d{3}) (?<body_bytes_sent>\d+) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)"
        Time_Key time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-metrics
  namespace: monitoring
spec:
  selector:
    app: fluent-bit
  ports:
    - name: metrics
      port: 2020
      targetPort: 2020
