apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-metrics
  namespace: monitoring
spec:
  selector:
    app: fluent-bit
  ports:
    - name: http-metrics
      port: 2020
      targetPort: 2020
