apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: monitoring
data:
  parsers.conf: |
    [PARSER]
        Name        nginx
        Format      regex
        Regex       ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<method>[A-Z]+) (?<request>[^ ]*) (?<protocol>[^"]*)" (?<status>[0-9]{3}) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)"
        Time_Key    time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z
