apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: monitoring
data:
  vault.hcl: |
    ui = true
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    storage "file" {
      path = "/vault/data"
    }
